services:
  # --- AUTH SERVICE ---
  auth-service:
    build:
      context: ./AuthMicroService
      dockerfile: ../Dockerfile
    container_name: auth-service
    environment:
      # Spring Boot userà questa variabile automaticamente
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SERVER_PORT=8081
      # JAVA_TOOL_OPTIONS viene letto automaticamente dalla JVM
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
    networks:
      - spendy-network

  # --- EXPENSE SERVICE ---
  expense-service:
    build:
      context: ./ExpenseMicroService
      dockerfile: ../Dockerfile
    container_name: expense-service
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SERVER_PORT=8084
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
    networks:
      - spendy-network

  # --- GATEWAY SERVICE ---
  gateway-service:
    build:
      context: ./Gateway
      dockerfile: ../Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080" # Unica porta esposta all'host
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
    depends_on:
      - auth-service
      - expense-service
    networks:
      - spendy-network

networks:
  spendy-network:
    driver: bridge