server.address=0.0.0.0
server.port=7860
spring.application.name=coinquylife-gateway
spring.threads.virtual.enabled=true

# Auth Service
spring.cloud.gateway.routes[0].id=coinquylifeauth
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URI}
spring.cloud.gateway.routes[0].predicates[0]=Path=/Auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/Auth/(?<segment>.*), /$\{segment}

# Expense Service
spring.cloud.gateway.routes[1].id=ExpenseMicroService
spring.cloud.gateway.routes[1].uri=${EXPENSE_SERVICE_URI}
spring.cloud.gateway.routes[1].predicates[0]=Path=/Expense/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/Expense/(?<segment>.*), /$\{segment}

# Token
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.http.server.reactive=INFO
logging.level.reactor.netty=INFO
logging.level.reactor.netty.http.client=ERROR

# Access Logs
reactor.netty.http.server.accessLogEnabled=true
logging.level.reactor.netty.http.server.AccessLog=INFO