spring.application.name=auth-service
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uuid-representation=standard
spring.threads.virtual.enabled=true
server.port=8081
logging.level.org.springframework.security=DEBUG


